apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baskidemo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/baskarp31/demo-argocd.git
    targetRevision: HEAD
    path: k8s-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: baskiargodemo
  syncPolicy:
    syncOptions:
      - syncTimeout=300s
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
